### ISSUE TITLE
Sinatra tutorials "IdeaBox" links to the previous WebGuesser project

### ISSUE THREAD

**Issue by phillipkregg** [ISS-SOA/class-SOA-repo#1]
Instead of linking to the Idea Box project, the link goes to the WebGuesser project from the previous example link.

Here's the correct link: http://tutorials.jumpstartlab.com/projects/idea_box.html

**Comment by soumyaray** [comment]
Hi @phillipkregg, are you sure you are commenting on the right repo?

**Comment by phillipkregg** [comment]
The problem is in the Wiki - under Ruby, Sinatra.  Here's a link: https://github.com/ISS-SOA/class-SOA-repo/wiki/resource-ruby-sinatra

Sorry I should have been more specific.

**Comment by soumyaray** [comment]
Ahh, my bad -- I haven't worked on this repo in a long time and don't really recall it very well.

I've fixed the link now (I think it points to what I had in mind once).

I don't really work with Sinatra anymore (moved on to Roda). I'm happy to make any and all fixes you suggest (PRs welcome), or you are welcome to also fork it if you wish.

Best of luck!
